//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por MiniMarket.rc
//
#define IDD_LOGIN                       102
#define IDD_REGISTRAR                   105
#define IDD_MODIFICAR                   107
#define IDD_TIENDA                      109
#define IDR_MENU1                       111
#define IDD_MIS_PRODUCTOS               112
#define IDD_AGREGAR_PRODUCTO            114
#define IDI_ICON1                       116
#define IDD_MODIFICAR_PRODUCTO          117
#define IDD_VER_PRODUCTO                119
#define IDD_CARRITO                     121
#define IDD_ALARMA                      123
#define IDC_EditPromoNombreAP           1001
#define IDC_EditContraM                 1002
#define IDC_EditNombreAP                1002
#define IDC_BtnIngresar                 1003
#define IDC_EditContraCM                1003
#define IDC_BtnModificar                1004
#define IDC_BtnRegistrar                1005
#define IDC_BtnFotoM                    1009
#define IDC_BtnModificarM               1010
#define IDC_EditFotoM                   1011
#define IDC_PicLogo                     1012
#define IDC_BtnRegresarM                1012
#define IDC_EditNombre                  1013
#define IDC_EditContra                  1014
#define IDC_PicFotoM                    1015
#define IDC_BtnRegresarR                1017
#define IDC_PicFotoR                    1018
#define IDC_EditNombreR                 1019
#define IDC_EditContraR                 1020
#define IDC_EditContraCR                1021
#define IDC_EditFotoR                   1022
#define IDC_BtnFotoR                    1023
#define IDC_BtnRegistrarR               1024
#define IDC_StNombreM                   1026
#define IDC_StIdM                       1027
#define IDC_ListaProductos              1028
#define IDC_BtnVerProducto              1029
#define IDC_BtnEliminarC                1030
#define IDC_BtnAddCarrito               1031
#define IDC_BtnEliminarProductoMy       1032
#define IDC_PicPerfilT                  1036
#define IDC_PicProductoT                1037
#define IDC_StProductoT                 1038
#define IDC_StUsuarioT                  1039
#define IDC_StPrecioT                   1040
#define IDC_BtnBusqueda                 1041
#define IDC_ListaProductosMy            1042
#define IDC_BtnTiendaMy                 1043
#define IDC_BtnVerCarritoMy             1044
#define IDC_BtnCerrarSesionMy           1045
#define IDC_PicProductoMy               1048
#define IDC_StProductoMy                1049
#define IDC_StPrecioMy                  1050
#define IDC_BtnAgregarProductoMy        1051
#define IDC_BtnModificarProductoMy      1052
#define IDC_BtnAntAP                    1054
#define IDC_BtnSigAP                    1055
#define IDC_EditDescAP                  1056
#define IDC_EditPrecioAP                1058
#define IDC_CbCategoAP                  1059
#define IDC_BtnFoto1AP                  1060
#define IDC_EditFoto1AP                 1061
#define IDC_BtnFoto2AP                  1062
#define IDC_EditFoto2AP                 1063
#define IDC_BtnAudioAP                  1064
#define IDC_EditAudioAP                 1065
#define IDC_EditPromoDescAP             1066
#define IDC_CheckPromoAP                1067
#define IDC_SliderPromoAP               1069
#define IDC_DateIniAP                   1070
#define IDC_TimeIniAP                   1071
#define IDC_DateFinAP                   1072
#define IDC_TimeFinAP                   1073
#define IDC_CbAlarmaAP                  1074
#define IDC_BtnReproAP                  1075
#define IDC_BtnDetenerAP                1076
#define IDC_BtnAgregarAP                1078
#define IDC_BtnTiendaAP                 1079
#define IDC_BtnRegresarAP               1080
#define IDC_BtnPlayAP                   1081
#define IDC_BtnPauseAP                  1082
#define IDC_BtnStopAP                   1083
#define IDC_StIdT                       1084
#define IDC_StIdMy                      1085
#define IDC_StUsuarioAP                 1086
#define IDC_StUsuarioMy                 1087
#define IDC_PicPerfilMy                 1088
#define IDC_StIdAP                      1089
#define IDC_PicPerfilAP                 1090
#define IDC_StPrecioFinalAP             1092
#define IDC_PicProductoAP               1093
#define IDC_StAudioAP                   1094
#define IDC_StPromocionAP               1095
#define IDC_StDescripcionAP             1096
#define IDC_StDescuentoAP               1097
#define IDC_StFechaIniAP                1098
#define IDC_StFechaFinAP                1099
#define IDC_StAlarmaAP                  1100
#define IDC_StPrecioFinAP               1101
#define IDC_StPorcentajeAP              1102
#define IDC_RadDesactivarAP             1104
#define IDC_RadActivarAP                1105
#define IDC_StPrecioAP                  1106
#define IDC_StTiempoAP                  1107
#define IDC_StIdMP                      1108
#define IDC_StUsuarioMP                 1109
#define IDC_PicPerfilMP                 1110
#define IDC_EditNombreMP                1111
#define IDC_EditDescMP                  1112
#define IDC_EditPrecioMP                1113
#define IDC_CbCategoMP                  1114
#define IDC_BtnFoto1MP                  1115
#define IDC_EditFoto1MP                 1116
#define IDC_BtnFoto2MP                  1117
#define IDC_EditFoto2MP                 1118
#define IDC_BtnAudioMP                  1119
#define IDC_StAudioMP                   1120
#define IDC_EditAudioMP                 1121
#define IDC_BtnPlayMP                   1122
#define IDC_BtnPauseMP                  1123
#define IDC_BtnStopMP                   1124
#define IDC_RadActivarMP                1125
#define IDC_RadDesactivarMP             1126
#define IDC_EditPromoNombreMP           1127
#define IDC_StPromocionMP               1128
#define IDC_StDescripcionMP             1129
#define IDC_EditPromoDescMP             1130
#define IDC_StDescuentoMP               1131
#define IDC_StPorcentajeMP              1132
#define IDC_SliderPromoMP               1133
#define IDC_StFechaIniMP                1134
#define IDC_DateIniMP                   1135
#define IDC_TimeIniMP                   1136
#define IDC_StFechaFinMP                1137
#define IDC_DateFinMP                   1138
#define IDC_TimeFinMP                   1139
#define IDC_StAlarmaMP                  1140
#define IDC_CbAlarmaMP                  1141
#define IDC_BtnReproMP                  1142
#define IDC_BtnDetenerMP                1143
#define IDC_StPrecioFinMP               1144
#define IDC_StPrecioFinalMP             1145
#define IDC_PicProductoMP               1146
#define IDC_BtnAntMP                    1147
#define IDC_BtnSigMP                    1148
#define IDC_BtnModificarMP              1149
#define IDC_BtnRegresarMP               1150
#define IDC_BtnTiendaMP                 1151
#define IDC_StPrecioMP                  1152
#define IDC_StTiempoMP                  1153
#define IDC_EditBuscarNombreT           1154
#define IDC_EditBuscarVendedorT         1155
#define IDC_CbBuscarCatT                1156
#define IDC_BtnAntVP                    1158
#define IDC_BtnSigVP                    1159
#define IDC_BtnCarritoVP                1160
#define IDC_BtnRegresarVP               1161
#define IDC_PicPerfilVP                 1162
#define IDC_StIdVP                      1163
#define IDC_StUsuarioVP                 1164
#define IDC_PicProductoVP               1165
#define IDC_StPromoVP                   1166
#define IDC_EditDescVP                  1167
#define IDC_StNombreVP                  1168
#define IDC_StCatVP                     1169
#define IDC_StVendedorVP                1170
#define IDC_EditAudioVP                 1171
#define IDC_BtnPlayVP                   1172
#define IDC_BtnPauseVP                  1173
#define IDC_BtnStopVP                   1174
#define IDC_StPrecioVP                  1175
#define IDC_StAudioVP                   1176
#define IDC_PicPerfilC                  1177
#define IDC_StIdC                       1178
#define IDC_StUsuarioC                  1179
#define IDC_ListaCarritoC               1180
#define IDC_PicProductoC                1181
#define IDC_StProductoC                 1182
#define IDC_StPrecioC                   1183
#define IDC_StAhorroC                   1184
#define IDC_StTotalC                    1185
#define IDC_BtnComprarC                 1186
#define IDC_BtnOkA                      1187
#define IDC_PicProductoA                1188
#define IDC_StAviso                     1189
#define IDC_StAvisoA                    1189
#define IDC_StNombreA                   1190
#define IDC_StPrecioA                   1191
#define IDC_StCategoriaA                1192
#define IDC_StVendedorA                 1193
#define IDC_MFCMENUBUTTON4              1231
#define ID_USUARIO_MISPRODUCTOS         40001
#define ID_USUARIO_MICARRITO            40002
#define ID_USUARIO_CERRARSESI40003      40003
#define ID_TIENDA_VERTODOSLOSPRODUCTOS  40004
#define ID_TIENDA_BUSCAR                40005
#define ID_CARRITO_VERCARRITO           40006
#define ID_CARRITO_VACIARCARRITO        40007
#define ID_SALIR_CERRARPROGRAMA         40008
#define ID_PRODUCTOS_MISPRODUCTOS       40009
#define ID_PRODUCTOS_AGREGARPRODUCTO    40010
#define ID_USUARIO_CERRARSESION         40011
#define ID_TIENDA_PRINCIPAL             40012
#define ID_USUARIO_ELIMINARCUENTA       40013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1232
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
